6th-ViewMyStartup-5team-FS/FS

client/package-lock.json
client/src/components/BtnLarge.jsx
client/src/components/BtnLeft.jsx
client/src/components/BtnMedium.jsx
client/src/components/BtnOutline.jsx
client/src/components/BtnPage.jsx
client/src/components/BtnRight.jsx
client/src/pages/MainFullList/index.jsx
client/src/pages/MainFullList/kimSukYoung.http

btns large 컴포넌트 
medium 컴포넌트 
outline 컴포넌트 
left/right 컴포넌트 
page 컴포넌트

[ 김수경 ] create btns large/medium/outline/left/right, page

---

client/src/components/BtnPage.jsx
client/src/components/BtnPagination.jsx
client/src/pages/MainFullList/kimSukYoung.http

[김수경] btn pagination component

---

client/src/components/BtnLarge.jsx
client/src/components/Dropdown.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/CompareBtn.jsx
client/src/pages/SelectCompany/CompareResult.module.css
client/src/pages/SelectCompany/CompareResults.jsx

[김수경] compareResultPage

---

client/src/components/BtnLarge.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/CompareResult.module.css
client/src/pages/SelectCompany/CompareResults.jsx
server/package-lock.json

[김수경] create media queary

---

client/package-lock.json
client/package.json
client/src/api/company.api.js
client/src/api/index.api.js
client/src/api/investment.api.js

src > api > index / company / investment .api.js  만드는 중입니다

[김수경] create api.js

---

client/src/components/BtnLarge.jsx
client/src/components/Input.jsx
client/src/components/modal/InvestmentModal.jsx
client/src/components/modal/PopupOneButton.jsx
client/src/pages/SelectCompany/CompareResult.module.css
client/src/pages/SelectCompany/CompareResults.jsx

비교 기업 결과 페이지에 사용되는 컴포넌트 업데이트 중입니다.

[김수경] update Investment Modal component

---

client/src/components/modal/InvestmentModal.jsx
client/src/components/modal/PopupOneButton.jsx
client/src/pages/SelectCompany/CompareResult.module.css
client/src/pages/SelectCompany/CompareResults.jsx

[김수경] update compareResultPage (8-10)

---

client/src/components/Dropdown.jsx

브랜치가 잘못되어있어 있만...
수정 내용은 dropdown 디자인 수정입니다 (border 색상, select와의 간격)

[김수경 ] dropdown 디자인 수정

---

client/src/components/Search.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx
client/src/pages/SelectCompany/MyCompanyComparison.module.css

- 선택취소 버튼 위치 수정 & search 바 크기 수정

[김다은] update search_size

---

client/src/components/Dropdown.jsx
server/https/companies.http

dropDown 디자인 수정
: select text 가운데 정렬

[김수경] update dropdown(positioin-center)

---

client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

[김다은] update/mycompany_modal

---

client/src/components/Dropdown.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/MainFullList/Homepage.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx
client/src/pages/SelectCompany/MyCompanyComparison.module.css
server/src/modules/companies.module.js

Revert "[김다은] update/mycompany&search"

---

client/src/pages/SelectCompany/MyCompanyComparison.jsx
client/src/pages/SelectCompany/MyCompanyComparison.module.css

- 나의 기업 선택하기 페이지에서 박스 윗부분 로고배치 수정

[김다은] update/mycompanylogo

---

client/src/components/modal/InvestmentModal.jsx
client/src/pages/CompanyDetail/index.jsx
client/src/pages/SelectCompany/CompareResults.jsx
server/https/companies.http

기업 상세 페이지에서
투자하기 모달의
기업정보를 하드코딩 > url 로 받도록 수정했습니다.

[김수경] update 'company-detail > investModal'

---

client/src/api/investment.api.js
client/src/components/modal/InvestmentModal.jsx
client/src/components/modal/PopupOneButton.jsx
client/src/pages/CompanyDetail/index.jsx

investmetn modal을 통해 투자 정보 생성할 수 있습니다.

[김수경] Feat/create invest inform

---

client/src/components/modal/SelectComparison.jsx
client/src/pages/MainFullList/Homepage.jsx

- Homepage와 SelectComparison 모달창에도 hangul.js 패치 완료!

[김다은] update: hangul.js_everywhere

---

client/src/components/modal/InvestmentModal.jsx
client/src/pages/SelectCompany/CompareResults.jsx

CompareResults, InvestmentModal 일부 수정

[최지예] 25.04.01 15:20 show investment modal with selected company info

---

client/src/components/modal/SelectMyEnterprise.jsx

[최지예] 25.04.01 16:02 update codes

---

client/package-lock.json
client/package.json
client/src/pages/SelectCompany/CompareResults.jsx

비교 기업 결과 페이지의 일부 항목 수정 (금액 + 텍스트)

[최지예] 25.04.01 19:11 update parts of parameters

---

client/src/main.jsx

기업 선택 횟수가 중복되는 것을 방지 (srtict mode를 제거해서 해결)

[김수경] erase STRICTMODE

---

client/src/components/modal/PopupOneButton.jsx
client/src/components/modal/UpdateInvestmentModal.jsx
client/src/pages/CompanyDetail/components/InvestmentTable.jsx
client/src/pages/CompanyDetail/index.jsx

기업 상세 페이지의 '수정하기', '삭제하기' 작동 구현 및 세부 사항 수정

[최지예] 25.04.02 10:46 edit InvestmentModal to update

---

client/src/pages/CompanyDetail/components/AmountCard.jsx
client/src/pages/CompanyDetail/index.jsx
client/src/styles/mixin.jsx

Reverts 6th-ViewMyStartup-5team-FS/FS#191

Revert "[신수민] updatae companyDetail Size"

---

server/src/modules/investments.module.js

기업상세페이지의 수정하기 부분 '투자자 이름'도 수정되도록 구현

[최지예] 25.04.02 14:13 edit apis/company-detail/update

---

client/src/components/modal/SelectComparison.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

[김다은] update: myCompanyModal2

---

client/src/components/modal/InvestmentModal.jsx
client/src/pages/SelectCompany/CompareResults.jsx

기업 결과 페이지에서 '나의 기업에 투자하기' 작동되도록 구현

[최지예] 25.04.02 16:17 re update codes for modal Investment in Page/compare-result

---

client/src/components/modal/SelectComparison.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

[김다은] update: doubledCompany delete

---

client/src/components/modal/Password.jsx
client/src/pages/SelectCompany/CompareResults.jsx
server/src/modules/resultCompares.module.js

기업 상세 페이지 > 투자 정부 > 수정, 삭제 버튼 클릭 시 모달이 오른쪽 하단에서 중안으로 이동하는 애니메이션 삭제.

[김수경] erase fade aminate

---

client/src/pages/SelectCompany/CompareResults.jsx

[최지예] re edit

---

client/src/components/Input.jsx
client/src/components/modal/InvestmentModal.jsx
client/src/components/modal/UpdateInvestmentModal.jsx

Reverts 6th-ViewMyStartup-5team-FS/FS#213

Revert "[신수민] update investmentModal"

---

client/src/api/investment.api.js
client/src/pages/CompanyDetail/components/InvestmentTable.jsx
server/src/modules/investments.module.js

[최지예] Page/compare result

---

client/src/components/Gnb.jsx
client/src/components/layout/MainLayout.jsx
client/src/pages/MainFullList/Homepage.jsx
client/src/pages/MainFullList/Homepage.module.css

[김수경] creating response mainPage

---

client/src/pages/SelectCompany/CompareResults.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

[김다은] Compare resetbtn

---

client/src/components/modal/SelectComparison.jsx
client/src/components/modal/SelectMyEnterprise.jsx
client/src/pages/SelectCompany/CompareResults.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

-  ‘다른 기업 비교하기’ 버튼 누르고 나서 SelectComparison에 ‘선택된 기업’ 기록도 그대로 남아있게 수정

[김다은] Update/compare resetbtn

---

client/src/api/index.api.js
client/src/api/rankings.api.js
client/src/pages/SelectCompany/CompareResults.jsx
client/src/pages/SelectCompany/MyCompanyComparison-DESKTOP-5G5CD06.jsx

'나의 기업 비교'페이지에서 
- '기업 순위 확인하기' 순위 정렬 잘 나오도록 수정
- '비교 결과 확인하기' 정렬 재수정

[최지예] 25.04.03 13:56 FE Fix sorting for page compare-result and Ranking sections

---

client/src/components/BtnLeft.jsx
client/src/components/BtnPage.jsx
client/src/components/BtnRight.jsx
client/src/components/Dropdown.jsx
client/src/components/Search.jsx
client/src/components/modal/SelectComparison.jsx
client/src/pages/MainFullList/Homepage.jsx
client/src/pages/MainFullList/Homepage.module.css

[김수경] response/mainPage/complete

---

client/src/pages/SelectCompany/CompareResults.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx

- 다른 기업 비교하기 버튼 기능 수정 
- 지예님께서 토스 받으실 예정

[김다은] update: 0404 CompareReset

---

client/src/pages/SelectCompany/CompareResults.jsx

다른 기업 비교하기 버튼 클릭 시 초기화되는 문제 해결

[최지예] 25.04.04 18:21 Fix: reset button and selected company on page refresh in /select-company and /select-company/compare-results

---

client/src/pages/CompanyDetail/index.jsx

기업 상세 페이지 내에 페이지네이션 부분(투자자 정보 불러오기) 완성입니다.

[김수경] feat/company-detail/pagenation

---

client/src/components/CompareListSection.jsx
client/src/pages/SelectCompany/CompareResult.module.css
client/src/pages/SelectCompany/CompareResults.jsx
client/src/pages/SelectCompany/MyCompanyComparison.jsx
client/src/pages/SelectCompany/MyCompanyComparison.module.css

my company comparison/compare results/compareListSection 반응형 수정

[이나경] Feat/0405 my company comparison/compare results/compareListSection

---

client/src/components/BtnLarge.jsx
client/src/components/Dropdown.jsx
client/src/components/modal/InvestmentModal.jsx
client/src/pages/CompareStatus/CompareStatus.module.css
client/src/pages/CompareStatus/index.jsx

- 드롭다운: 사용하는 모든 페이지에서 보기 좋게 나오도록 다듬었어요
- 버튼라지: "" 일 경우의 props를 몇개 더 추가했어요
- 투자하기 모달: 피그마 기준으로 전체적으로 수정

[김다은] update: dropdown&btnlarge&investModal

---

server/src/db/prisma/seed.js

[최지예] Update seed.js

---

server/src/db/prisma/seed.js

Reverts 6th-ViewMyStartup-5team-FS/FS#292

Revert "[신수민] add seed 3 line"

---

client/src/pages/CompanyDetail/index.jsx

[최지예] 25.04.07 16:46 made scroll bars

---

client/src/pages/CompanyDetail/index.jsx

[최지예] 25.04.07 18:52 restore: made scroll bars

---

client/src/pages/CompanyDetail/index.jsx
server/src/modules/investments.module.js
server/src/modules/resultCompares.module.js

모바일일 경우(small media size), 회색 스크롤바 구현

25.04.08 10:47 re edit scroll(media size: small)

---

client/src/pages/CompanyDetail/index.jsx
client/src/pages/InvestStatus/investStatus.module.css
client/src/pages/SelectCompany/CompareResults.jsx
server/src/modules/investments.module.js
server/src/modules/resultCompares.module.js

[최지예] 25.04.08 14:01 add scroll to page/compare-result(media size:  small)

---

client/src/pages/CompareStatus/index.jsx

[최지예] 25.04.08 14:14 edit scroll color to page/compare-status(medi a size: small)

---

client/src/pages/MainFullList/Homepage.jsx

홈페이지의 스크롤 색상 회색 및 디자인 피그마처럼 변경

[최지예] 25.04.08 14:24 edit scroll color to page/homepage(media size : small)
